name: Ansible deploy
on: 
  push:
    branches: 
    - testing  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.7
      uses: actions/setup-python@v3
      with:
        python-version: 3.7
    - name: Install Ansible
      run: |
        sudo apt update
        sudo apt install ansible -y
        ansible --version
    - name: Creating Ansible Machine
      env: 
        MY_KEY: ${{ secrets.PRIVATE }}
      run: |
        echo $PWD 
        echo $USER
        sudo service sshd start
        mkdir /home/$USER/.ssh
        echo "$MY_KEY" > /home/$USER/.ssh/id_rsa      
        sudo chmod 400 /home/$USER/.ssh/id_rsa
        sudo service sshd restart
        ls -al /home/$USER/.ssh
    - name: Pinging through Ansible
      run: |
       ssh -i home/$USER/.ssh/id_rsa -o StrictHostKeyChecking=false ubuntu@13.229.126.226
       #ansible-playbook -i ./inventory ./myplay.yml
       ansible -i ./inventory workers -m ping 
